name: 15-minute-cron
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: |
          curl --request GET \
          --url 'https://bransan.vercel.app/api/update'
